updating calentre's readme file
Calentre/calentre-client pull request #26
Opened 2024-03-07 18:41 UTC by luisflores93

updating calentre's readme file

2024-03-07 18:54 UTC, fiizzy commented on README.md
> +# Calentre 📅💰
We need to change this to Calentre-Client

2024-03-07 19:05 UTC, fiizzy commented on README.md
> +Welcome to Calentre, the open-source alternative to Calendly! 🌟 Manage your appointments, get paid, and enjoy the scheduling experience.
"Welcome to the Client (invitee) side of Calentre. This repo contains the code that allows on invitee (client) to book a meeting based on the schedule of the admin (meeting owner) "

2024-03-07 19:07 UTC, fiizzy commented on README.md
> +<img src = "https://github.com/fiizzy/calentre/blob/main/doc/images/booking.png?raw=true" >
Let's take out this image, and replace it with Client image. A screenshot can be taken from your dev app.

2024-03-07 19:10 UTC, fiizzy requested changes
Generally looking good. But we want the ReadMe to be focused only on the Client.

2024-03-07 19:10 UTC, fiizzy commented on README.md
> +- **Customization:** Tailor the scheduling process to match your style.
These features should be relative to Calentre-Client only.

2024-03-07 19:10 UTC, fiizzy commented on README.md
> +For more, check the [User Guide](doc/user-guide.md).
Can you also edit this to also just talk about Calentre Client.

2024-03-07 19:57 UTC, luisflores93 commented on README.md
> +For more, check the [User Guide](doc/user-guide.md).
@Jessica-Andrew could you help me with this content 😅

2024-03-07 19:57 UTC, luisflores93 commented on README.md
> +- **Customization:** Tailor the scheduling process to match your style.
@Jessica-Andrew could you help me with this content 😅

2024-03-10 22:28 UTC, fiizzy approved these changes
Going to approve this ✅

2024-03-10 22:28 UTC, merged